# Site settings
title: Burgerlijst
email: info@burgerlijst.be
description: > # this means to ignore newlines until "baseurl:"
  Dit is de website van de Burgerlijst, een kieslijst
  die gaat voor conflictvrije en participatieve democratie.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.burgerlijst.be" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
